apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flui-backend-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  
  source:
    repoURL: https://github.com/IanJairo/flui-backend.git
    targetRevision: main
    path: helm
    helm:
      releaseName: flui-backend-prod
      valueFiles:
        - values-prod.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: flui-prod
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
