apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-cluster-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  
  source:
    repoURL: https://github.com/IanJairo/flui-backend-gitops.git
    targetRevision: main
    path: manifests/postgres-prod
  
  destination:
    server: https://kubernetes.default.svc
    namespace: flui-prod
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
