apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster
  namespace: flui-back-dev
spec:
  instances: 1
  
  storage:
    size: 2Gi
    storageClass: hostpath
  
  bootstrap:
    initdb:
      database: flui_dev
      owner: flui
      secret:
        name: postgres-superuser
  
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "128MB"
  
  monitoring:
    enablePodMonitor: false
