apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-operator
  namespace: argocd
spec:
  project: default
  
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 15.5.32
    helm:
      releaseName: postgres
      parameters:
        - name: auth.username
          value: postgres
        - name: auth.password
          value: postgres
        - name: auth.database
          value: flui_dev
        - name: primary.persistence.size
          value: 2Gi
  
  destination:
    server: https://kubernetes.default.svc
    namespace: flui-back-dev 
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
