apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-cluster-prod
  namespace: flui-prod
spec:
  instances: 3 
  
  storage:
    size: 10Gi
    storageClass: hostpath
  
  bootstrap:
    initdb:
      database: flui_prod 
      owner: flui         
      secret:
        name: postgres-superuser-prod
  
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      work_mem: "4MB"
      maintenance_work_mem: "64MB"
    pg_hba:
      - host all all all scram-sha-256
  
  monitoring:
    enablePodMonitor: false
  
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"
